name: assignment
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - pip=23.3.1
  - pip:
    - scikit-learn
    - pandas==2.2.0
    - matplotlib==3.8.3
    - xlrd==2.0.1
    - pyarrow==15.0.0
    - statsmodels==0.14.0
    - openpyxl==3.1.2
    - plotly==5.19.0
    - seaborn==0.11.2
    - tqdm==4.66.2
